site_name: django-tailwind-cli
repo_name: oliverandrich/django-tailwind-cli
repo_url: https://github.com/oliverandrich/django-tailwind-cli
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: "purple"
      accent: "purple"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: "purple"
      accent: "purple"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font: false
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
nav:
  - Home: "index.md"
  - "installation.md"
  - "usage.md"
  - "settings.md"
  - "template_tags.md"
  - "base_template.md"
  - Changelog: "changelog.md"
markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - footnotes
  - tables
  - pymdownx.snippets:
      check_paths: true
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@oliverandrich
    - icon: fontawesome/brands/github
      link: https://github.com/oliverandrich
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/oliver-andrich-3a6a97200/
copyright: Copyright &copy; 2023 Oliver Andrich
